steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/grobel-dev', './client']
  # - name: 'gcr.io/cloud-builders/docker'
  # args: ['build', '-t', 'gcr.io/$PROJECT_ID/grobel-dev-server', './server']

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grobel-dev']
  # - name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'gcr.io/$PROJECT_ID/grobel-dev-server']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'grobel-dev',
        '--image',
        'gcr.io/$PROJECT_ID/grobel-dev',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
        '--allow-unauthenticated',
      ]
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'grobel-dev-server',
  #       '--image',
  #       'gcr.io/$PROJECT_ID/grobel-dev-server',
  #       '--region',
  #       'us-central1',
  #       '--platform',
  #       'managed',
  #       '--quiet',
  #       '--allow-unauthenticated',
  #     ]

images:
  - gcr.io/$PROJECT_ID/grobel-dev
  # - gcr.io/$PROJECT_ID/grobel-dev-server
